name = "zalo-bot-hoa-ngoc"
main = "src/index.js"
compatibility_date = "2025-09-24"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "BOT_STORAGE"
id = "dbde16950a7b4b3d8e814d97a566540b"

[vars]
# Các biến không nhạy cảm
ZALO_APP_ID = "4391377450967727174"
