/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SanPhamRouteImport } from './routes/san-pham'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SanPhamSlugRouteImport } from './routes/san-pham.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamRoute = SanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamSlugRoute = SanPhamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SanPhamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/san-pham': typeof SanPhamRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/san-pham': typeof SanPhamRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/san-pham': typeof SanPhamRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gioi-thieu'
    | '/lien-he'
    | '/san-pham'
    | '/sitemap.xml'
    | '/san-pham/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gioi-thieu'
    | '/lien-he'
    | '/san-pham'
    | '/sitemap.xml'
    | '/san-pham/$slug'
  id:
    | '__root__'
    | '/'
    | '/gioi-thieu'
    | '/lien-he'
    | '/san-pham'
    | '/sitemap.xml'
    | '/san-pham/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GioiThieuRoute: typeof GioiThieuRoute
  LienHeRoute: typeof LienHeRoute
  SanPhamRoute: typeof SanPhamRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham': {
      id: '/san-pham'
      path: '/san-pham'
      fullPath: '/san-pham'
      preLoaderRoute: typeof SanPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$slug': {
      id: '/san-pham/$slug'
      path: '/$slug'
      fullPath: '/san-pham/$slug'
      preLoaderRoute: typeof SanPhamSlugRouteImport
      parentRoute: typeof SanPhamRoute
    }
  }
}

interface SanPhamRouteChildren {
  SanPhamSlugRoute: typeof SanPhamSlugRoute
}

const SanPhamRouteChildren: SanPhamRouteChildren = {
  SanPhamSlugRoute: SanPhamSlugRoute,
}

const SanPhamRouteWithChildren =
  SanPhamRoute._addFileChildren(SanPhamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GioiThieuRoute: GioiThieuRoute,
  LienHeRoute: LienHeRoute,
  SanPhamRoute: SanPhamRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
