/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SanPhamRouteImport } from './routes/san-pham'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as ChinhSachThanhToanRouteImport } from './routes/chinh-sach-thanh-toan'
import { Route as ChinhSachGiaoHangRouteImport } from './routes/chinh-sach-giao-hang'
import { Route as ChinhSachDoiTraRouteImport } from './routes/chinh-sach-doi-tra'
import { Route as ChinhSachBaoMatRouteImport } from './routes/chinh-sach-bao-mat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TheIndexRouteImport } from './routes/the.index'
import { Route as SanPhamIndexRouteImport } from './routes/san-pham.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TheTagRouteImport } from './routes/the.$tag'
import { Route as SanPhamSlugRouteImport } from './routes/san-pham.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SanPhamRoute = SanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachThanhToanRoute = ChinhSachThanhToanRouteImport.update({
  id: '/chinh-sach-thanh-toan',
  path: '/chinh-sach-thanh-toan',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachGiaoHangRoute = ChinhSachGiaoHangRouteImport.update({
  id: '/chinh-sach-giao-hang',
  path: '/chinh-sach-giao-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachDoiTraRoute = ChinhSachDoiTraRouteImport.update({
  id: '/chinh-sach-doi-tra',
  path: '/chinh-sach-doi-tra',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachBaoMatRoute = ChinhSachBaoMatRouteImport.update({
  id: '/chinh-sach-bao-mat',
  path: '/chinh-sach-bao-mat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheIndexRoute = TheIndexRouteImport.update({
  id: '/the/',
  path: '/the/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamIndexRoute = SanPhamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SanPhamRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheTagRoute = TheTagRouteImport.update({
  id: '/the/$tag',
  path: '/the/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamSlugRoute = SanPhamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SanPhamRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chinh-sach-doi-tra': typeof ChinhSachDoiTraRoute
  '/chinh-sach-giao-hang': typeof ChinhSachGiaoHangRoute
  '/chinh-sach-thanh-toan': typeof ChinhSachThanhToanRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/san-pham': typeof SanPhamRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/the/$tag': typeof TheTagRoute
  '/blog/': typeof BlogIndexRoute
  '/san-pham/': typeof SanPhamIndexRoute
  '/the/': typeof TheIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chinh-sach-doi-tra': typeof ChinhSachDoiTraRoute
  '/chinh-sach-giao-hang': typeof ChinhSachGiaoHangRoute
  '/chinh-sach-thanh-toan': typeof ChinhSachThanhToanRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/the/$tag': typeof TheTagRoute
  '/blog': typeof BlogIndexRoute
  '/san-pham': typeof SanPhamIndexRoute
  '/the': typeof TheIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chinh-sach-doi-tra': typeof ChinhSachDoiTraRoute
  '/chinh-sach-giao-hang': typeof ChinhSachGiaoHangRoute
  '/chinh-sach-thanh-toan': typeof ChinhSachThanhToanRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/san-pham': typeof SanPhamRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/the/$tag': typeof TheTagRoute
  '/blog/': typeof BlogIndexRoute
  '/san-pham/': typeof SanPhamIndexRoute
  '/the/': typeof TheIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chinh-sach-bao-mat'
    | '/chinh-sach-doi-tra'
    | '/chinh-sach-giao-hang'
    | '/chinh-sach-thanh-toan'
    | '/gioi-thieu'
    | '/lien-he'
    | '/san-pham'
    | '/blog/$slug'
    | '/san-pham/$slug'
    | '/the/$tag'
    | '/blog/'
    | '/san-pham/'
    | '/the/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chinh-sach-bao-mat'
    | '/chinh-sach-doi-tra'
    | '/chinh-sach-giao-hang'
    | '/chinh-sach-thanh-toan'
    | '/gioi-thieu'
    | '/lien-he'
    | '/blog/$slug'
    | '/san-pham/$slug'
    | '/the/$tag'
    | '/blog'
    | '/san-pham'
    | '/the'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chinh-sach-bao-mat'
    | '/chinh-sach-doi-tra'
    | '/chinh-sach-giao-hang'
    | '/chinh-sach-thanh-toan'
    | '/gioi-thieu'
    | '/lien-he'
    | '/san-pham'
    | '/blog/$slug'
    | '/san-pham/$slug'
    | '/the/$tag'
    | '/blog/'
    | '/san-pham/'
    | '/the/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChinhSachBaoMatRoute: typeof ChinhSachBaoMatRoute
  ChinhSachDoiTraRoute: typeof ChinhSachDoiTraRoute
  ChinhSachGiaoHangRoute: typeof ChinhSachGiaoHangRoute
  ChinhSachThanhToanRoute: typeof ChinhSachThanhToanRoute
  GioiThieuRoute: typeof GioiThieuRoute
  LienHeRoute: typeof LienHeRoute
  SanPhamRoute: typeof SanPhamRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  TheTagRoute: typeof TheTagRoute
  BlogIndexRoute: typeof BlogIndexRoute
  TheIndexRoute: typeof TheIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/san-pham': {
      id: '/san-pham'
      path: '/san-pham'
      fullPath: '/san-pham'
      preLoaderRoute: typeof SanPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-thanh-toan': {
      id: '/chinh-sach-thanh-toan'
      path: '/chinh-sach-thanh-toan'
      fullPath: '/chinh-sach-thanh-toan'
      preLoaderRoute: typeof ChinhSachThanhToanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-giao-hang': {
      id: '/chinh-sach-giao-hang'
      path: '/chinh-sach-giao-hang'
      fullPath: '/chinh-sach-giao-hang'
      preLoaderRoute: typeof ChinhSachGiaoHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-doi-tra': {
      id: '/chinh-sach-doi-tra'
      path: '/chinh-sach-doi-tra'
      fullPath: '/chinh-sach-doi-tra'
      preLoaderRoute: typeof ChinhSachDoiTraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-bao-mat': {
      id: '/chinh-sach-bao-mat'
      path: '/chinh-sach-bao-mat'
      fullPath: '/chinh-sach-bao-mat'
      preLoaderRoute: typeof ChinhSachBaoMatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the/': {
      id: '/the/'
      path: '/the'
      fullPath: '/the/'
      preLoaderRoute: typeof TheIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/': {
      id: '/san-pham/'
      path: '/'
      fullPath: '/san-pham/'
      preLoaderRoute: typeof SanPhamIndexRouteImport
      parentRoute: typeof SanPhamRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the/$tag': {
      id: '/the/$tag'
      path: '/the/$tag'
      fullPath: '/the/$tag'
      preLoaderRoute: typeof TheTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$slug': {
      id: '/san-pham/$slug'
      path: '/$slug'
      fullPath: '/san-pham/$slug'
      preLoaderRoute: typeof SanPhamSlugRouteImport
      parentRoute: typeof SanPhamRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SanPhamRouteChildren {
  SanPhamSlugRoute: typeof SanPhamSlugRoute
  SanPhamIndexRoute: typeof SanPhamIndexRoute
}

const SanPhamRouteChildren: SanPhamRouteChildren = {
  SanPhamSlugRoute: SanPhamSlugRoute,
  SanPhamIndexRoute: SanPhamIndexRoute,
}

const SanPhamRouteWithChildren =
  SanPhamRoute._addFileChildren(SanPhamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChinhSachBaoMatRoute: ChinhSachBaoMatRoute,
  ChinhSachDoiTraRoute: ChinhSachDoiTraRoute,
  ChinhSachGiaoHangRoute: ChinhSachGiaoHangRoute,
  ChinhSachThanhToanRoute: ChinhSachThanhToanRoute,
  GioiThieuRoute: GioiThieuRoute,
  LienHeRoute: LienHeRoute,
  SanPhamRoute: SanPhamRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  TheTagRoute: TheTagRoute,
  BlogIndexRoute: BlogIndexRoute,
  TheIndexRoute: TheIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
